
from .nodes import CO_CLIENT,CO_CHAT,CO_QUESION

NODE_CLASS_MAPPINGS = {
    "CO_CLIENT": CO_CLIENT,
    "CO_CHAT": CO_CHAT,
    "CO_QUESION": CO_QUESION,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "CO_CLIENT": "CO_CLIENT",
    "CO_CHAT": "CO_CHAT",
    "CO_QUESION": "CO_QUESION",
}
__all__ = [NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS]